# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_session', models.BooleanField()),
                ('token', models.CharField(max_length=200)),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ponderation', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(1, 'Choix multiple'), (2, 'Choix unique'), (3, 'Maybe relevant'), (4, 'Text à trou')], default=1)),
                ('statement', models.CharField(max_length=200)),
                ('is_answer', models.BooleanField()),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('audio', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('ponderation', models.IntegerField(default=1)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(1, 'Choix multiple'), (2, 'Choix unique'), (3, 'Maybe relevant'), (4, 'Text à trou')], default=1)),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='id_enonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Test'),
        ),
        migrations.AddField(
            model_name='enonce',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Test'),
        ),
        migrations.AddField(
            model_name='choice',
            name='id_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='postings.Question'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='session_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='postings.Session'),
        ),
    ]
