# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20190308_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
