# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20190308_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(default='non', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.CharField(default='non', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='candidatsession',
            name='token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='choice',
            name='statement',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='audio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='statement',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='video',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
