# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20190308_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
