# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_auto_20190308_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enonce',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enonce',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
